---
engines:
  duplication:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      comma-dangle:
        enabled: false
      global-require:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - bin
  - node_modules
  - coverage
  - dist
